/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamification.views;

import gamification.domain.*;
import java.util.*;

/**
 *
 * @author Mateo
 */
public class VentanaFlashCards extends javax.swing.JFrame {

    ArrayList<String> preguntas = new ArrayList<>();
    ArrayList<String> respuestas = new ArrayList<>();
    private int contador = 0;
    private boolean mostrarRespuesta = false;

    /**
     * Creates new form VentanaFlashCards
     */
    public VentanaFlashCards() {
        initComponents();
    }

    public VentanaFlashCards(ArrayList<Tema> temasSeleccionados) {
        cargarTemas(temasSeleccionados);
        initComponents();
        mostrarPregunta();

    }

    public void cargarTemas(ArrayList<Tema> temasSeleccionados) {
        String titulo = "";
        for (Tema tema : temasSeleccionados) {
            //titulo
            titulo = titulo + " " + tema.getNombre();

            //carga preguntas
            for (String pregunta : tema.getPreguntas().keySet()) {
                preguntas.add(pregunta);
            }

            //carga respuestas
            for (String respuesta : tema.getPreguntas().values()) {
                respuestas.add(respuesta);
            }

        }

        this.setTitle(titulo);

    }

    public void mostrarPregunta() {
        String texto;
        if (mostrarRespuesta) {
            texto = respuestas.get(contador);
        } else {
            texto = preguntas.get(contador);
        }

        btnPregunta.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPregunta = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnPregunta.setText("Pregunta/Respuesta");
        btnPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPregunta);
        btnPregunta.setBounds(80, 70, 230, 100);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior);
        btnAnterior.setBounds(90, 210, 90, 22);

        btnAtras.setText("Siguiente");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(220, 210, 90, 22);

        setSize(new java.awt.Dimension(424, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (contador > 0) {
            contador--;
        }
        mostrarRespuesta = false;
        mostrarPregunta();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        if (contador < preguntas.size() - 1) {
            contador++;

        }
        mostrarRespuesta = false;
        mostrarPregunta();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntaActionPerformed
        // TODO add your handling code here:
        mostrarRespuesta = !mostrarRespuesta;
        mostrarPregunta();
    }//GEN-LAST:event_btnPreguntaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFlashCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnPregunta;
    // End of variables declaration//GEN-END:variables
}
