/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamification.views;

import java.awt.*;
import java.awt.event.*;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;

/**
 *
 * @author Mateo
 */
public final class VentanaMemory extends javax.swing.JFrame {

    private HashMap<String, String> preguntas = new HashMap<>();
    private String[] preguntasOrdenadas = new String[12];
    private String[] preguntasDesordenadas = new String[12];
    private String[][] textos = new String[3][4];
    private String[][] tipos = new String[3][4];
    private boolean[][] activos = new boolean[3][4];
    private JButton[][] botones;
    private boolean ayudaParcial = false;
    private boolean ayudaTotal = false;

    /**
     * Creates new form VentanaMemory
     *
     * @param titulo
     * @param preguntasSinFiltrar
     */
    public VentanaMemory(String titulo, HashMap<String, String> preguntasSinFiltrar) {
        this.filtrarPreguntas(preguntasSinFiltrar);
        setPreguntasOrdenadas(preguntas);
        preguntasDesordenadas = desordenarPreguntas(preguntasOrdenadas);
        initComponents();
        crearBotones();
        actualizarTablero();
    }

    public void setPreguntasOrdenadas(HashMap<String, String> preguntasSinFiltrar) {
        int index = 0;
        for (Map.Entry<String, String> entry : preguntasSinFiltrar.entrySet()) {
            Object key = entry.getKey();
            Object val = entry.getValue();
            preguntasOrdenadas[index] = (String) key;
            index++;
            preguntasOrdenadas[index] = (String) val;
            index++;
        }
    }

    public String[] desordenarPreguntas(String[] preguntasOrdenadas) {
        String[] ar = preguntasOrdenadas.clone();
        Random rnd = new Random();

        for (int i = ar.length - 1; i > 0; i--) {
            int index = rnd.nextInt(i + 1);
            // Simple swap
            String a = ar[index];
            ar[index] = ar[i];
            ar[i] = a;
        }

        return ar;
    }

    public void filtrarPreguntas(HashMap<String, String> preguntasSinFiltrar) {
        Set<String> keySet = preguntasSinFiltrar.keySet();
        ArrayList<String> keys = new ArrayList<>(keySet);

        Random r = new Random();

        for (int i = 0; i < 6; i++) {
            int randomNumber = r.nextInt(keys.size());
            String pregunta = keys.get(randomNumber);
            keys.remove(pregunta);
            this.preguntas.put(pregunta, preguntasSinFiltrar.get(pregunta));
        }
    }

    public void crearBotones() {
        int index = 0;
        int cantFilas = 3;
        int cantColumnas = 4;
        botones = new JButton[cantFilas][cantColumnas];
        for (int i = 0; i < cantFilas; i++) {
            for (int j = 0; j < cantColumnas; j++) {
                JButton jButton = new JButton();
                jButton.addActionListener(new ListenerBoton(i, j));
                panelInferior.add(jButton);
                botones[i][j] = jButton;

                textos[i][j] = preguntasDesordenadas[index];
                index++;

                String tipo;
                if (preguntas.containsKey(textos[i][j])) {
                    tipo = "PREGUNTA";
                    botones[i][j].setForeground(Color.BLUE);
                } else {
                    tipo = "RESPUESTA";
                    botones[i][j].setForeground(Color.RED);
                }
                tipos[i][j] = tipo;

                botones[i][j].setMargin(new Insets(-5, -5, -5, -5));
                //botones[i][j].setBackground(Color.RED);
                botones[i][j].setText("<html><p>" + "BOTON" + "</p></html>");

            }
        }
    }
    
    public void actualizarTablero(){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 4; j++) {
                if(ayudaTotal){
                    botones[i][j].setText(textos[i][j]);
                }else if(ayudaParcial){
                    botones[i][j].setText(tipos[i][j]);
                }else{                
                    if(activos[i][j]){
                        botones[i][j].setText(textos[i][j]);
                    }else{
                        botones[i][j].setText("");
                    }
                }    
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        btnAyudaParcial = new javax.swing.JButton();
        btnAyudaTotal = new javax.swing.JButton();
        btnText = new javax.swing.JButton();
        btnSonido = new javax.swing.JButton();
        lblPuntaje = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        btnAyudaParcial.setText("Ayuda Parcial");
        btnAyudaParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaParcialActionPerformed(evt);
            }
        });
        panelSuperior.add(btnAyudaParcial);

        btnAyudaTotal.setText("Ayuda Total");
        btnAyudaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaTotalActionPerformed(evt);
            }
        });
        panelSuperior.add(btnAyudaTotal);

        btnText.setText("Reset");
        btnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextActionPerformed(evt);
            }
        });
        panelSuperior.add(btnText);

        btnSonido.setText("Sonido");
        btnSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonidoActionPerformed(evt);
            }
        });
        panelSuperior.add(btnSonido);

        lblPuntaje.setText("Puntaje: ---");
        panelSuperior.add(lblPuntaje);

        getContentPane().add(panelSuperior);

        panelInferior.setLayout(new java.awt.GridLayout(3, 4));
        getContentPane().add(panelInferior);

        setBounds(0, 0, 414, 337);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonidoActionPerformed
        // TODO add your handling code here:

        try {
            Clip clip = AudioSystem.getClip();
            URL url = this.getClass().getClassLoader().getResource("../resources/melodyloop.mp3");
            AudioInputStream inputStream = AudioSystem.getAudioInputStream(url);
            clip.open(inputStream);
            clip.start();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }//GEN-LAST:event_btnSonidoActionPerformed

    private void btnAyudaParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaParcialActionPerformed
        // TODO add your handling code here:
        ayudaParcial = !ayudaParcial;
        actualizarTablero();
    }//GEN-LAST:event_btnAyudaParcialActionPerformed

    private void btnAyudaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaTotalActionPerformed
        // TODO add your handling code here:
        ayudaTotal = !ayudaTotal;
        actualizarTablero();
    }//GEN-LAST:event_btnAyudaTotalActionPerformed

    private void btnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextActionPerformed
        // TODO add your handling code here:
        ayudaTotal = false;
        ayudaParcial = false;
        actualizarTablero();
    }//GEN-LAST:event_btnTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(String titulo, HashMap preguntas) {
                new VentanaMemory(titulo, preguntas).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyudaParcial;
    private javax.swing.JButton btnAyudaTotal;
    private javax.swing.JButton btnSonido;
    private javax.swing.JButton btnText;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables

    private class ListenerBoton implements ActionListener {

        private int x;
        private int y;

        public ListenerBoton(int fila, int col) {
            // en el constructor se almacena la fila y columna que se presion�
            x = fila;
            y = col;
        }

        public void actionPerformed(ActionEvent e) {
            // cuando se presiona un bot�n, se ejecutar� este m�todo
            clickBoton(x, y);
        }
    }

    private void clickBoton(int fila, int col) {
        // M�todo a completar!.
        // En fila y columna se reciben las coordenas donde presion� el usuario, relativas al comienzo de la grilla
        // fila 0 y columna 0 corresponden a la posici�n de arriba a la izquierda.
        // Debe indicarse c�mo responder al click de ese bot�n.
        botones[fila][col].setText(textos[fila][col]);
    }
}
