/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamification.views;

import gamification.domain.Sistema;
import gamification.domain.Tema;

/**
 *
 * @author Mateo
 */
public class VentanaTemas extends javax.swing.JFrame {

    private Sistema modelo;

    /**
     * Creates new form VentanaTemas
     */
    public VentanaTemas() {
        initComponents();
    }

    public VentanaTemas(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
        cargarLista();
    }

    private void cargarLista() {
        lstTemas.setListData(modelo.getListaTemas().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTemas = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Temas");
        getContentPane().setLayout(null);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(20, 30, 240, 36);

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(20, 90, 240, 90);

        jLabel1.setText("Nombre;");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 50, 19);

        jLabel2.setText("Descripcion:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 80, 19);

        lstTemas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstTemas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTemasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstTemas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 40, 160, 140);

        jLabel3.setText("Lista:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 20, 70, 19);

        btnAgregarModificar.setText("Agregar/Modificar");
        btnAgregarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarModificar);
        btnAgregarModificar.setBounds(20, 220, 140, 40);

        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(170, 220, 140, 40);

        btnEliminar1.setText("Preguntas");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar1);
        btnEliminar1.setBounds(320, 220, 130, 40);

        setBounds(0, 0, 477, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnAgregarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarModificarActionPerformed
        // TODO add your handling code here:
        Tema tema = new Tema(txtNombre.getText(), txtDescripcion.getText());
        Tema agregarTema = modelo.agregarTema(tema);
        cargarLista();
    }//GEN-LAST:event_btnAgregarModificarActionPerformed

    private void lstTemasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTemasValueChanged
        // TODO add your handling code here:
        try {
            Tema tema = (Tema) lstTemas.getSelectedValue();
            txtNombre.setText(tema.getNombre());
            txtDescripcion.setText(tema.getDescripcion());
        } catch (Exception NullPointerException) {

        }
    }//GEN-LAST:event_lstTemasValueChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Tema tema = (Tema) lstTemas.getSelectedValue();
        modelo.eliminarTema(tema);
        cargarLista();

        txtNombre.setText("");
        txtDescripcion.setText("");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Tema tema = (Tema) lstTemas.getSelectedValue();
        VentanaPreguntas view = new VentanaPreguntas(tema);
        view.setVisible(true);

    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarModificar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstTemas;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
